✨ Fix percyCSS not getting applied when elements outside `</body>`
percy/cli pull request #1415
Opened 2023-10-27 12:55 UTC by itsjwala

TBA

fixes https://github.com/percy/cli/issues/489

2023-10-27 13:33 UTC, ninadbstack commented on packages/core/src/config.js
> +        type: 'boolean'
That would deviate from long term goal of having every possible property with default value in config though [ with 1 line comments in even longer term ]

2023-10-27 13:36 UTC, ninadbstack commented on packages/core/src/discovery.js
> +    let elementsOutsideBodySerializationWarningRegex = /<\/body>/;
This regex looks pretty generic, maybe we can make it slightly more explanatory

2023-10-27 13:39 UTC, itsjwala commented on packages/core/src/config.js
> +        type: 'boolean'
hmm, yeah reverting for now.

2023-10-30 06:38 UTC, ChinoJones requested changes
💭

2023-10-30 12:14 UTC, shantanuk-browserstack approved these changes

2023-10-30 12:54 UTC, merged